version: 1

build:
  tools:
    python: "3.9"

sphinx:
  fail_on_warning: true

python:  
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf
  - epub