[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ige-docs"
authors = [{name = "Indi Games", email = "admin@indigames.net"}]
dynamic = ["version", "description"]
